cookie:
  expiry_days: 30
  key: 1010abczyx1010
  name: testing
credentials:
  usernames:
    dp:
      email: deeppatel0306@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Deep
      password: $2b$12$bQkeB2c9sPbAmDGiYzXjV.YAy1ZfbMYLtHvBcFP/HKfTLKbhewrJ.
pre-authorized:
  emails:
  - dr507498@gmail.com